### ISSUE TITLE
Add some cool python stuff and learning resource

### ISSUE THREAD

**Issue by sunilsj99** [sunilsj99/Python-Material#1]
Add some cool python stuff and learning resource

**Comment by simplymanas** [comment]
https://github.com/vinta/awesome-python do you want to try that

**Comment by sunilsj99** [comment]
@simplymanas Thanks for the link.
I want some good resource to learn python

**Comment by simplymanas** [comment]
start by learning a book and work on the exercise, the above link is pretty good. Youtube free tutorials can help you a lot
